### ISSUE TITLE
Problem: can't parse Expression from XML

### ISSUE THREAD

**Issue by yrashk** [bpxe/bpxe#1]
The problem seem to be related to the fact that `Expression` has not only text but also attributes and children elements.
https://github.com/bpxe/bpxe.rs/blob/master/src/bpmn/schema/autogenerated.rs#L5796-L5815

How to reproduce: run `cargo test -- --ignored`

The error:

```
---- parse_sample stdout ----
thread 'parse_sample' panicked at 'called `Result::unwrap()` on an `Err` value: ParsingError { error: UnexpectedToken { token: "Ok(Text { text: StrSpan(\"\\n    \" 980..985) })" } }', tests/bpmn_test.rs:7:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
https://github.com/bpxe/bpxe.rs/blob/master/tests/bpmn_test.rs#L4-L9

Proposed solution #1: find and fix a bug in strong-xml

Proposed solution #2: write own deserialization derivation

**Comment by SoftwareApe** [comment]
This seems to still be a problem with strong-xml, did you file an issue there?

**Comment by yrashk** [comment]
@SoftwareApe this is most likely an issue with strong-xml and I didn't file this as the maintainer doesn't seem to be responsive. I've opened issues there before and received no acknowledgment.
